-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 13:06:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `addressesId` INT NOT NULL AUTO_INCREMENT,
  `str_name` VARCHAR(45) NOT NULL,
  `str_number` INT NOT NULL,
  `floor` INT NOT NULL,
  `door` VARCHAR(5) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addressesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suppliers` (
  `NIF` INT NOT NULL,
  `phoneNumber` INT(9) NOT NULL,
  `fax` INT(9) NOT NULL,
  `supplierName` VARCHAR(45) NOT NULL,
  `Addresses_addressesId` INT NOT NULL,
  PRIMARY KEY (`NIF`),
  INDEX `fk_Suppliers_Addresses_idx` (`Addresses_addressesId` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_Addresses`
    FOREIGN KEY (`Addresses_addressesId`)
    REFERENCES `mydb`.`Addresses` (`addressesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `name` VARCHAR(30) NOT NULL,
  `phone` INT(9) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registrationDate` DATE NOT NULL,
  `recomendedBy` VARCHAR(45) NULL,
  `Clients_phone` INT(9) NULL,
  PRIMARY KEY (`phone`),
  INDEX `fk_recomended_idx` (`Clients_phone` ASC) VISIBLE,
  CONSTRAINT `fk_recomended`
    FOREIGN KEY (`Clients_phone`)
    REFERENCES `mydb`.`Clients` (`phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `glassesId` INT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `left_graduation` FLOAT NOT NULL,
  `right_graduation` FLOAT NOT NULL,
  `frame` NCHAR(15) NOT NULL,
  `frame_color` VARCHAR(45) NOT NULL,
  `left_glass_color` VARCHAR(45) NOT NULL,
  `right_glass_color` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `Suppliers_NIF` INT NOT NULL,
  PRIMARY KEY (`glassesId`),
  INDEX `fk_Glasses_Suppliers1_idx` (`Suppliers_NIF` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Suppliers1`
    FOREIGN KEY (`Suppliers_NIF`)
    REFERENCES `mydb`.`Suppliers` (`NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sells`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sells` (
  `sellId` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `price` FLOAT NOT NULL,
  `Clients_phone` INT(9) NOT NULL,
  `Glasses_glassesId` INT NOT NULL,
  `vendor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sellId`),
  INDEX `fk_Sells_Clients1_idx` (`Clients_phone` ASC) VISIBLE,
  INDEX `fk_Sells_Glasses1_idx` (`Glasses_glassesId` ASC) VISIBLE,
  CONSTRAINT `fk_Sells_Clients1`
    FOREIGN KEY (`Clients_phone`)
    REFERENCES `mydb`.`Clients` (`phone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sells_Glasses1`
    FOREIGN KEY (`Glasses_glassesId`)
    REFERENCES `mydb`.`Glasses` (`glassesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
